/* ============================================================
   ExpediFun — content & i18n data
   English = native, Spanish = secondary
============================================================ */
window.UI = {
  en:{
    nav_packages:"Experiences", nav_about:"About", nav_contact:"Contact", nav_signin:"Sign in", nav_explore:"Explore trips",
    packagesIn:"Experiences in", pkTitle:"Choose your next experience.",
    pkNote:"Save your favorites with the heart and build a list for future vacations. No cart — every experience is quoted to fit you.",
    from:"from", per:"/person", request:"Book",
    discover:"Discover", galleryNote:"A glimpse of the culture, flavors and landscapes that await you.",
    g_beaches:"Beaches", g_culture:"Culture & history", g_food:"Gastronomy", g_nature:"Nature", g_nightlife:"Nightlife", g_people:"People",
    about_eyebrow:"About us", about_title:"Travel, made simple and local.",
    about_p1:"ExpediFun is a multi-service company that curates authentic travel experiences through trusted local operators. We started in the Caribbean and we are growing destination by destination.",
    about_p2:"No endless checkouts and no hidden fees — you tell us what you dream of, and our local teams build it for you with transparent, market-fair pricing.",
    about_s1:"Local operators", about_s2:"Destinations", about_s3:"Traveler rating",
    cancel_eyebrow:"Cancellation policies", cancel_title:"Clear, fair and flexible.",
    cancel_items:[
      {h:"Free cancellation up to 48 h", p:"Cancel up to 48 hours before the experience starts and get a 100% refund, no questions asked."},
      {h:"24–48 h before", p:"Cancellations within 24 to 48 hours of the start time receive a 50% refund."},
      {h:"Less than 24 h", p:"Cancellations under 24 hours before the start time are non-refundable."},
      {h:"Weather & force majeure", p:"If an experience is cancelled by the operator due to weather, you may reschedule at no cost or receive a full refund."}
    ],
    contact_eyebrow:"Contact us", contact_title:"Let's plan your trip.",
    contact_note:"Tell us what you have in mind and our local team will get back to you with a tailored quote.",
    f_name:"Name", f_email:"Email", f_phone:"Phone", f_message:"Message", f_send:"Send message", f_sent:"Thanks! We'll be in touch shortly.",
    foot_tagline:"Authentic travel experiences, powered by trusted local operators.",
    foot_company:"Company", foot_legal:"Legal", foot_destinations:"Destinations", foot_contact:"Contact",
    l_about:"About us", l_how:"How it works", l_packages:"Experiences", l_contact:"Contact",
    l_terms:"Terms & conditions", l_privacy:"Privacy policy", l_cancel:"Cancellation policies",
    foot_rights:"ExpediFun LLC — a Wyoming company. All rights reserved.",
    foot_license:"Tourism operating licenses in process with the Ministry of Tourism (MITUR).",
    foot_pay:"Secure payments via Stripe.",
    franchise:"Destination:", loading:"Loading", construction:"Under construction",
    nav_transfers:"Transfers",
    tr_eyebrow:"Transfers", tr_title:"Get there, stress-free.",
    tr_note:"Private airport and hotel transfers run by vetted local operators. Tap an operator to see their fleet, routes and book — your details reach their trip sheet automatically.",
    tr_book:"Book transfer", tr_view:"View operator →", tr_from:"from", tr_oneway:"one way", tr_serves:"Serves",
    op_rating:"rating", op_trips:"transfers", op_fleet:"Fleet", op_routes:"Popular routes & rates",
    op_book_title:"Book a transfer with", op_book_note:"In a live booking these details land on the operator's trip sheet automatically — name, flight, pickup time and place.",
    tf_type:"Trip type", tf_oneway:"One way", tf_round:"Round trip",
    tf_from:"Pickup location", tf_to:"Destination", tf_date:"Pickup date", tf_time:"Pickup time",
    tf_pax:"Passengers", tf_flight:"Flight no. (optional)", tf_country:"Country of residence",
    tf_notes:"Notes (luggage, child seat, etc.)", tf_submit:"Request transfer", tf_done:"Request sent! The operator will confirm your transfer shortly.",
    si_title:"Welcome back", si_sub:"Sign in to manage your trips and saved favorites.",
    si_email:"Email", si_pass:"Password", si_signin:"Sign in", si_google:"Continue with Google", si_or:"or",
    si_no_acct:"New to ExpediFun?", si_create:"Create an account", si_have_acct:"Already have an account?",
    su_title:"Create your account", su_name:"Full name", su_create:"Create account", si_signin_link:"Sign in",
    si_demo:"Demo preview — accounts aren't active yet.",
    pm_date:"Date", pm_time:"Time", pm_travelers:"Travelers", pm_pax:"Passengers",
    pm_pickup:"Pickup location", pm_dropoff:"Destination", pm_flight:"Flight no. (optional)",
    pm_summary:"Price summary", pm_subtotal:"Subtotal", pm_taxes:"Taxes & fees", pm_total:"Total",
    pm_payment:"Payment", pm_card:"Card number", pm_pay:"Confirm & pay", pm_per:"per person", pm_reviews:"reviews",
    pm_secure:"Secure checkout · powered by Stripe", pm_free_cancel:"Free cancellation up to 48 h before",
    pm_done:"Booking confirmed — see you there! (demo)",
    saved_title:"Your saved trips", saved_empty:"No favorites yet — tap the heart on any experience to save it."
  },
  es:{
    nav_packages:"Experiencias", nav_about:"Nosotros", nav_contact:"Contacto", nav_signin:"Iniciar sesión", nav_explore:"Explorar viajes",
    packagesIn:"Experiencias en", pkTitle:"Escoge tu próxima experiencia.",
    pkNote:"Guarda tus favoritos con el corazón y arma tu lista para futuras vacaciones. Sin carrito — cada experiencia se cotiza a tu medida.",
    from:"desde", per:"/pers.", request:"Reservar",
    discover:"Descubre", galleryNote:"Un vistazo a la cultura, los sabores y los paisajes que te esperan.",
    g_beaches:"Playas", g_culture:"Cultura e historia", g_food:"Gastronomía", g_nature:"Naturaleza", g_nightlife:"Vida nocturna", g_people:"Gente",
    about_eyebrow:"Nosotros", about_title:"Viajar, simple y local.",
    about_p1:"ExpediFun es una compañía multi-servicios que cura experiencias de viaje auténticas a través de operadores locales de confianza. Empezamos en el Caribe y crecemos destino a destino.",
    about_p2:"Sin checkouts eternos ni cargos ocultos — tú nos dices lo que sueñas y nuestros equipos locales lo arman para ti, con precios transparentes y justos.",
    about_s1:"Operadores locales", about_s2:"Destinos", about_s3:"Valoración de viajeros",
    cancel_eyebrow:"Políticas de cancelación", cancel_title:"Claras, justas y flexibles.",
    cancel_items:[
      {h:"Cancelación gratis hasta 48 h", p:"Cancela hasta 48 horas antes del inicio de la experiencia y recibe el 100% de reembolso, sin preguntas."},
      {h:"Entre 24 y 48 h antes", p:"Las cancelaciones entre 24 y 48 horas antes del inicio reciben un 50% de reembolso."},
      {h:"Menos de 24 h", p:"Las cancelaciones con menos de 24 horas de anticipación no son reembolsables."},
      {h:"Clima y fuerza mayor", p:"Si el operador cancela por clima, puedes reprogramar sin costo o recibir un reembolso completo."}
    ],
    contact_eyebrow:"Contáctanos", contact_title:"Planeemos tu viaje.",
    contact_note:"Cuéntanos lo que tienes en mente y nuestro equipo local te responderá con una cotización a tu medida.",
    f_name:"Nombre", f_email:"Correo", f_phone:"Teléfono", f_message:"Mensaje", f_send:"Enviar mensaje", f_sent:"¡Gracias! Te contactaremos en breve.",
    foot_tagline:"Experiencias de viaje auténticas, con operadores locales de confianza.",
    foot_company:"Compañía", foot_legal:"Legal", foot_destinations:"Destinos", foot_contact:"Contacto",
    l_about:"Nosotros", l_how:"Cómo funciona", l_packages:"Experiencias", l_contact:"Contacto",
    l_terms:"Términos y condiciones", l_privacy:"Política de privacidad", l_cancel:"Políticas de cancelación",
    foot_rights:"ExpediFun LLC — una empresa de Wyoming. Todos los derechos reservados.",
    foot_license:"Licencias de operación turística en trámite con el Ministerio de Turismo (MITUR).",
    foot_pay:"Pagos seguros vía Stripe.",
    franchise:"Destino:", loading:"Cargando", construction:"En construcción",
    nav_transfers:"Traslados",
    tr_eyebrow:"Traslados", tr_title:"Llega sin estrés.",
    tr_note:"Traslados privados de aeropuerto y hotel con operadores locales verificados. Toca un operador para ver su flota, rutas y reservar — sus datos llegan a la hoja de viaje del operador automáticamente.",
    tr_book:"Reservar traslado", tr_view:"Ver operador →", tr_from:"desde", tr_oneway:"por trayecto", tr_serves:"Cubre",
    op_rating:"valoración", op_trips:"traslados", op_fleet:"Flota", op_routes:"Rutas y tarifas populares",
    op_book_title:"Reserva un traslado con", op_book_note:"En una reserva real estos datos llegan a la hoja de viaje del operador automáticamente — nombre, vuelo, hora y lugar de recogida.",
    tf_type:"Tipo de viaje", tf_oneway:"Solo ida", tf_round:"Ida y vuelta",
    tf_from:"Lugar de recogida", tf_to:"Destino", tf_date:"Fecha de recogida", tf_time:"Hora de recogida",
    tf_pax:"Pasajeros", tf_flight:"N.º de vuelo (opcional)", tf_country:"País de residencia",
    tf_notes:"Notas (equipaje, silla de niño, etc.)", tf_submit:"Solicitar traslado", tf_done:"¡Solicitud enviada! El operador confirmará tu traslado en breve.",
    si_title:"Bienvenido de nuevo", si_sub:"Inicia sesión para gestionar tus viajes y favoritos guardados.",
    si_email:"Correo", si_pass:"Contraseña", si_signin:"Iniciar sesión", si_google:"Continuar con Google", si_or:"o",
    si_no_acct:"¿Nuevo en ExpediFun?", si_create:"Crear una cuenta", si_have_acct:"¿Ya tienes cuenta?",
    su_title:"Crea tu cuenta", su_name:"Nombre completo", su_create:"Crear cuenta", si_signin_link:"Iniciar sesión",
    si_demo:"Vista demo — las cuentas aún no están activas.",
    pm_date:"Fecha", pm_time:"Hora", pm_travelers:"Viajeros", pm_pax:"Pasajeros",
    pm_pickup:"Lugar de recogida", pm_dropoff:"Destino", pm_flight:"N.º de vuelo (opcional)",
    pm_summary:"Resumen de precio", pm_subtotal:"Subtotal", pm_taxes:"Impuestos y cargos", pm_total:"Total",
    pm_payment:"Pago", pm_card:"Número de tarjeta", pm_pay:"Confirmar y pagar", pm_per:"por persona", pm_reviews:"reseñas",
    pm_secure:"Pago seguro · con Stripe", pm_free_cancel:"Cancelación gratis hasta 48 h antes",
    pm_done:"¡Reserva confirmada — nos vemos allí! (demo)",
    saved_title:"Tus viajes guardados", saved_empty:"Aún no tienes favoritos — toca el corazón en cualquier experiencia para guardarla."
  }
};

window.LOCATIONS = {
  do:{ flag:"🇩🇴", place:{en:"Dominican Republic",es:"República Dominicana"},
    welcome:{en:"Welcome to",es:"Bienvenido a"}, currency:"US$",
    sub:{en:"Untouched beaches, turquoise water and experiences tailored to you.",
         es:"Playas vírgenes, agua turquesa y experiencias hechas a tu medida."},
    packages:[
      {loc:"Saona Island",   price:"119", name:{en:"Saona Island — Premium",es:"Isla Saona — Premium"}, desc:{en:"Natural pool, palm-fringed beach and catamaran in a small group.",es:"Piscina natural, playa de palmeras y catamarán en grupo reducido."}},
      {loc:"Bávaro",         price:"139", name:{en:"Buggy & Zipline Combo",es:"Combo Buggy y Zipline"}, desc:{en:"Off-road buggy through the countryside plus a 6-line zipline and Blue Lagoon cenote.",es:"Buggy todoterreno por el campo, zipline de 6 líneas y cenote Blue Lagoon."}},
      {loc:"Cap Cana",       price:"129", name:{en:"Hoyo Azul & Scape Park",es:"Hoyo Azul y Scape Park"}, desc:{en:"Turquoise cenote, ziplines and trails inside Cap Cana's natural park.",es:"Cenote turquesa, tirolesas y senderos en el parque natural de Cap Cana."}},
      {loc:"La Romana",      price:"89",  name:{en:"Catalina Island Snorkel",es:"Snorkel Isla Catalina"}, desc:{en:"Snorkel a vibrant reef and relax on a white-sand Caribbean island.",es:"Snorkel en arrecife vibrante y descanso en isla caribeña de arena blanca."}},
      {loc:"Santo Domingo",  price:"95",  name:{en:"Colonial City Tour",es:"Tour Ciudad Colonial"}, desc:{en:"Walk the first city of the Americas: Zona Colonial, Alcázar and local flavors.",es:"Recorre la primera ciudad de América: Zona Colonial, Alcázar y sabores locales."}},
      {loc:"Samaná",         price:"115", name:{en:"Samaná & El Limón Falls",es:"Samaná y Salto El Limón"}, desc:{en:"Horseback ride to a 50 m waterfall and a boat to Cayo Levantado.",es:"Cabalgata a una cascada de 50 m y bote a Cayo Levantado."}},
      {loc:"Bávaro",         price:"69",  name:{en:"Catamaran Party Cruise",es:"Catamarán Party Cruise"}, desc:{en:"Open-bar catamaran, snorkel stop and a natural pool off Bávaro's coast.",es:"Catamarán con barra libre, parada de snorkel y piscina natural en Bávaro."}},
      {loc:"Samaná Bay",     price:"99",  name:{en:"Los Haitises Park",es:"Parque Los Haitises"}, desc:{en:"Mangroves, caves with Taíno art and rich birdlife by boat.",es:"Manglares, cuevas con arte taíno y abundante avifauna en bote."}},
      {loc:"Macao",          price:"75",  name:{en:"Macao Beach Buggy",es:"Buggy Playa Macao"}, desc:{en:"Dune-buggy ride to Macao Beach with a stop at a local cave cenote.",es:"Buggy hasta Playa Macao con parada en un cenote local."}}
    ]},
  co:{ flag:"🇨🇴", place:{en:"Colombia",es:"Colombia"},
    welcome:{en:"Welcome to",es:"Bienvenido a"}, currency:"US$",
    sub:{en:"Caribbean shores, coffee country and vibrant cities in one trip.",
         es:"Caribe, café y ciudades vibrantes en un solo viaje."},
    packages:[
      {loc:"Cartagena",    price:"85",  name:{en:"Walled City Tour",es:"Tour Ciudad Amurallada"}, desc:{en:"Historic center, San Felipe castle and golden-hour viewpoints.",es:"Centro histórico, castillo San Felipe y miradores al atardecer."}},
      {loc:"Cartagena",    price:"95",  name:{en:"Rosario Islands Catamaran",es:"Catamarán Islas del Rosario"}, desc:{en:"Sail to coral islands with snorkeling and beach time.",es:"Navega a islas de coral con snorkel y playa."}},
      {loc:"Coffee Region",price:"79",  name:{en:"Coffee Farm Experience",es:"Experiencia Finca Cafetera"}, desc:{en:"Pick, roast and taste coffee on a working farm.",es:"Recolecta, tuesta y prueba café en una finca activa."}},
      {loc:"Salento",      price:"69",  name:{en:"Cocora Valley Hike",es:"Caminata Valle de Cocora"}, desc:{en:"Walk among the world's tallest wax palms.",es:"Camina entre las palmas de cera más altas del mundo."}},
      {loc:"Antioquia",    price:"89",  name:{en:"Guatapé & El Peñol",es:"Guatapé y El Peñol"}, desc:{en:"Climb the famous rock and tour the colorful town.",es:"Sube la famosa piedra y recorre el pueblo colorido."}},
      {loc:"Santa Marta",  price:"99",  name:{en:"Tayrona National Park",es:"Parque Tayrona"}, desc:{en:"Jungle trails to wild Caribbean beaches.",es:"Senderos de selva a playas caribeñas vírgenes."}},
      {loc:"San Andrés",   price:"110", name:{en:"Sea of Seven Colors",es:"Mar de Siete Colores"}, desc:{en:"Snorkel reefs and visit Johnny Cay.",es:"Snorkel en arrecifes y visita a Johnny Cay."}},
      {loc:"Medellín",     price:"65",  name:{en:"City & Comuna 13",es:"Ciudad y Comuna 13"}, desc:{en:"Street art, cable cars and the story of a reborn city.",es:"Arte urbano, metrocable y la historia de una ciudad renacida."}},
      {loc:"Meta",         price:"260", name:{en:"Caño Cristales Day",es:"Día Caño Cristales"}, desc:{en:"The river of five colors (seasonal), flights included.",es:"El río de cinco colores (temporada), vuelos incluidos."}}
    ]},
  mx:{ flag:"🇲🇽", place:{en:"Mexico",es:"México"},
    welcome:{en:"Welcome to",es:"Bienvenido a"}, currency:"US$",
    sub:{en:"Beaches, cenotes and ancient culture at your own pace.",
         es:"Playa, cenotes y cultura milenaria a tu ritmo."},
    packages:[
      {loc:"Yucatán",      price:"99",  name:{en:"Chichén Itzá & Cenote",es:"Chichén Itzá y Cenote"}, desc:{en:"A wonder of the world plus a swim in a sacred cenote.",es:"Una maravilla del mundo y un baño en un cenote sagrado."}},
      {loc:"Quintana Roo", price:"89",  name:{en:"Tulum Ruins & Beach",es:"Ruinas de Tulum y Playa"}, desc:{en:"Clifftop ruins over the Caribbean and free beach time.",es:"Ruinas sobre el Caribe y tiempo libre en la playa."}},
      {loc:"Cozumel",      price:"95",  name:{en:"Cozumel Reef Snorkel",es:"Snorkel Arrecife Cozumel"}, desc:{en:"Snorkel one of the world's top reef systems.",es:"Snorkel en uno de los mejores arrecifes del mundo."}},
      {loc:"Riviera Maya", price:"139", name:{en:"Xcaret Park",es:"Parque Xcaret"}, desc:{en:"Underground rivers, culture and an evening show.",es:"Ríos subterráneos, cultura y espectáculo nocturno."}},
      {loc:"Cancún",       price:"85",  name:{en:"Isla Mujeres Catamaran",es:"Catamarán Isla Mujeres"}, desc:{en:"Open-bar sail, snorkel and beach club access.",es:"Navegación con barra libre, snorkel y club de playa."}},
      {loc:"Mexico City",  price:"79",  name:{en:"Teotihuacán Pyramids",es:"Pirámides de Teotihuacán"}, desc:{en:"Climb the Sun and Moon pyramids with a guide.",es:"Sube las pirámides del Sol y la Luna con guía."}},
      {loc:"Riviera Maya", price:"110", name:{en:"Cenotes Adventure",es:"Aventura de Cenotes"}, desc:{en:"Swim and snorkel three hidden cenotes.",es:"Nada y haz snorkel en tres cenotes escondidos."}},
      {loc:"Mexico City",  price:"69",  name:{en:"Xochimilco & Coyoacán",es:"Xochimilco y Coyoacán"}, desc:{en:"Colorful trajineras and Frida Kahlo's neighborhood.",es:"Trajineras coloridas y el barrio de Frida Kahlo."}},
      {loc:"Tulum",        price:"129", name:{en:"Sian Ka'an Biosphere",es:"Biosfera Sian Ka'an"}, desc:{en:"Float a natural canal in a UNESCO reserve.",es:"Flota en un canal natural dentro de una reserva UNESCO."}}
    ]},
  pr:{ flag:"🇵🇷", place:{en:"Puerto Rico",es:"Puerto Rico"},
    welcome:{en:"Welcome to",es:"Bienvenido a"}, currency:"US$",
    sub:{en:"Bioluminescent bays, old-town charm and rainforest in one island.",
         es:"Bahías bioluminiscentes, casco antiguo y selva en una sola isla."},
    packages:[
      {loc:"Fajardo",      price:"69",  name:{en:"Bioluminescent Bay Kayak",es:"Kayak Bahía Bioluminiscente"}, desc:{en:"Paddle a glowing lagoon after dark.",es:"Rema en una laguna que brilla en la oscuridad."}},
      {loc:"San Juan",     price:"55",  name:{en:"Old San Juan Walking Tour",es:"Tour Viejo San Juan"}, desc:{en:"Forts, plazas and 500 years of history.",es:"Fortalezas, plazas y 500 años de historia."}},
      {loc:"Río Grande",   price:"89",  name:{en:"El Yunque Rainforest",es:"Bosque El Yunque"}, desc:{en:"Waterfalls and trails in the only U.S. tropical rainforest.",es:"Cascadas y senderos en la única selva tropical de EE. UU."}},
      {loc:"Culebra",      price:"99",  name:{en:"Culebra & Flamenco Beach",es:"Culebra y Playa Flamenco"}, desc:{en:"Ferry to one of the world's best beaches.",es:"Ferry a una de las mejores playas del mundo."}},
      {loc:"Vieques",      price:"115", name:{en:"Vieques Snorkel & Beach",es:"Snorkel y Playa Vieques"}, desc:{en:"Wild beaches and reefs off the east coast.",es:"Playas salvajes y arrecifes en la costa este."}},
      {loc:"Camuy",        price:"95",  name:{en:"Camuy Caves & Arecibo",es:"Cuevas del Camuy y Arecibo"}, desc:{en:"Vast caverns and the iconic observatory site.",es:"Cavernas inmensas y el icónico observatorio."}},
      {loc:"Fajardo",      price:"105", name:{en:"Catamaran to Icacos",es:"Catamarán a Icacos"}, desc:{en:"Sail and snorkel a deserted cay.",es:"Navega y haz snorkel en un cayo desierto."}},
      {loc:"Ponce",        price:"65",  name:{en:"Ponce Cultural Tour",es:"Tour Cultural Ponce"}, desc:{en:"The 'Pearl of the South' and its museums.",es:"La 'Perla del Sur' y sus museos."}},
      {loc:"San Juan",     price:"59",  name:{en:"Rum Distillery & Tasting",es:"Destilería de Ron y Cata"}, desc:{en:"Behind the scenes of Puerto Rican rum.",es:"Tras bambalinas del ron puertorriqueño."}}
    ]},
  us:{ flag:"🇺🇸", place:{en:"United States",es:"Estados Unidos"},
    welcome:{en:"Welcome to",es:"Bienvenido a"}, currency:"US$",
    sub:{en:"Iconic cities, national parks and bucket-list experiences coast to coast.",
         es:"Ciudades icónicas, parques nacionales y experiencias de ensueño de costa a costa."},
    packages:[
      {loc:"New York",      price:"79",  name:{en:"Statue of Liberty & Ellis Island",es:"Estatua de la Libertad e Isla Ellis"}, desc:{en:"Ferry to Liberty Island and the immigration museum with skyline views.",es:"Ferry a la Isla de la Libertad y el museo de inmigración con vistas al skyline."}},
      {loc:"New York",      price:"129", name:{en:"Broadway Show & Times Square",es:"Show de Broadway y Times Square"}, desc:{en:"Reserved seats to a top musical plus an evening city walk.",es:"Asientos reservados a un musical top y paseo nocturno por la ciudad."}},
      {loc:"Las Vegas",     price:"399", name:{en:"Grand Canyon Helicopter",es:"Helicóptero al Gran Cañón"}, desc:{en:"Fly over the Strip and land inside the Grand Canyon.",es:"Vuela sobre el Strip y aterriza dentro del Gran Cañón."}},
      {loc:"Orlando",       price:"159", name:{en:"Theme Park Day Pass",es:"Pase de Día a Parque Temático"}, desc:{en:"Skip-the-line access to a top Orlando theme park.",es:"Acceso sin filas a un parque temático top de Orlando."}},
      {loc:"San Francisco", price:"95",  name:{en:"Alcatraz & Bay Cruise",es:"Alcatraz y Crucero por la Bahía"}, desc:{en:"Tour the legendary island prison and sail under the Golden Gate.",es:"Recorre la legendaria prisión y navega bajo el Golden Gate."}},
      {loc:"Miami",         price:"69",  name:{en:"Everglades Airboat",es:"Hidrodeslizador en los Everglades"}, desc:{en:"Airboat through the wetlands and meet the wildlife.",es:"Hidrodeslizador por los humedales y fauna salvaje."}},
      {loc:"Los Angeles",   price:"75",  name:{en:"Hollywood & Celebrity Homes",es:"Hollywood y Casas de Famosos"}, desc:{en:"Walk of Fame, the Hollywood Sign and Beverly Hills.",es:"Paseo de la Fama, el letrero de Hollywood y Beverly Hills."}},
      {loc:"Hawaii",        price:"189", name:{en:"Pearl Harbor & Honolulu",es:"Pearl Harbor y Honolulu"}, desc:{en:"USS Arizona Memorial and a guided island tour.",es:"Memorial USS Arizona y tour guiado por la isla."}}
    ]},
  es:{ flag:"🇪🇸", place:{en:"Spain",es:"España"},
    welcome:{en:"Welcome to",es:"Bienvenido a"}, currency:"€",
    sub:{en:"Sun-drenched coasts, Moorish palaces and world-class food and wine.",
         es:"Costas soleadas, palacios moriscos y gastronomía y vino de primer nivel."},
    packages:[
      {loc:"Barcelona",     price:"59",  name:{en:"Sagrada Família Skip-the-Line",es:"Sagrada Família sin Filas"}, desc:{en:"Guided entry to Gaudí's masterpiece basilica.",es:"Entrada guiada a la basílica obra maestra de Gaudí."}},
      {loc:"Madrid",        price:"49",  name:{en:"Prado Museum & Old Madrid",es:"Museo del Prado y Madrid Antiguo"}, desc:{en:"Masterpieces of the Prado plus the historic center.",es:"Obras maestras del Prado y el centro histórico."}},
      {loc:"Granada",       price:"65",  name:{en:"Alhambra & Generalife",es:"Alhambra y Generalife"}, desc:{en:"Skip-the-line tour of the Nasrid palaces and gardens.",es:"Tour sin filas de los palacios nazaríes y jardines."}},
      {loc:"Seville",       price:"55",  name:{en:"Alcázar & Flamenco Night",es:"Alcázar y Noche de Flamenco"}, desc:{en:"Royal palace by day, live flamenco by night.",es:"Palacio real de día, flamenco en vivo de noche."}},
      {loc:"Mallorca",      price:"89",  name:{en:"Tramuntana Coast Catamaran",es:"Catamarán Costa de Tramuntana"}, desc:{en:"Sail hidden coves with snorkel and lunch aboard.",es:"Navega calas escondidas con snorkel y almuerzo a bordo."}},
      {loc:"San Sebastián", price:"79",  name:{en:"Pintxos & Wine Walk",es:"Ruta de Pintxos y Vino"}, desc:{en:"Taste the Basque country's legendary bar food.",es:"Prueba la legendaria comida de barra del País Vasco."}},
      {loc:"Valencia",      price:"45",  name:{en:"City of Arts & Sciences",es:"Ciudad de las Artes y las Ciencias"}, desc:{en:"Futuristic architecture and Europe's top aquarium.",es:"Arquitectura futurista y el mejor acuario de Europa."}},
      {loc:"Ibiza",         price:"95",  name:{en:"Sunset Boat & Es Vedrà",es:"Barco al Atardecer y Es Vedrà"}, desc:{en:"Cruise to the iconic islet for golden-hour views.",es:"Navega al icónico islote para ver el atardecer."}}
    ]}
};

/* ============================================================
   Transfer operators — PER DESTINATION (the service runs inside
   each country). FPO data; clickable in the Transfers section.
============================================================ */
window.TRANSFERS={
  do:[
    { id:"caribe-shuttle", name:"Caribe Shuttle Co.", flag:"🇩🇴", currency:"US$",
      tagline:{en:"Airport and resort transfers across Punta Cana and the Dominican east coast.",es:"Traslados de aeropuerto y resorts en Punta Cana y el este dominicano."},
      rating:"4.9", trips:"12,400+", serves:{en:"Punta Cana · La Romana · Santo Domingo",es:"Punta Cana · La Romana · Santo Domingo"},
      fleet:[{en:"Sedan · 1–3 pax",es:"Sedán · 1–3 pax"},{en:"SUV · 1–5 pax",es:"SUV · 1–5 pax"},{en:"Van · 1–10 pax",es:"Van · 1–10 pax"}],
      routes:[{from:"Punta Cana Airport (PUJ)",to:"Bávaro hotels",price:"35",min:"25"},{from:"Punta Cana Airport (PUJ)",to:"Cap Cana",price:"45",min:"30"},{from:"La Romana Airport (LRM)",to:"Bayahíbe",price:"40",min:"20"}]},
    { id:"bavaro-express", name:"Bávaro Express", flag:"🇩🇴", currency:"US$",
      tagline:{en:"Fast shared and private shuttles for the Bávaro and Uvero Alto hotel strip.",es:"Shuttles compartidos y privados para la zona hotelera de Bávaro y Uvero Alto."},
      rating:"4.7", trips:"8,100+", serves:{en:"Punta Cana · Bávaro · Uvero Alto",es:"Punta Cana · Bávaro · Uvero Alto"},
      fleet:[{en:"Shared shuttle",es:"Shuttle compartido"},{en:"Private SUV · 1–5 pax",es:"SUV privado · 1–5 pax"},{en:"Minibus · 1–16 pax",es:"Minibús · 1–16 pax"}],
      routes:[{from:"Punta Cana Airport (PUJ)",to:"Uvero Alto",price:"50",min:"40"},{from:"Punta Cana Airport (PUJ)",to:"Punta Cana Village",price:"30",min:"20"},{from:"Santo Domingo (SDQ)",to:"Boca Chica",price:"35",min:"25"}]},
    { id:"dr-premium", name:"DR Premium Rides", flag:"🇩🇴", currency:"US$",
      tagline:{en:"Private chauffeur service island-wide, with meet & greet at arrivals.",es:"Servicio privado con chofer en toda la isla, con recepción en llegadas."},
      rating:"5.0", trips:"3,400+", serves:{en:"Island-wide · private chauffeur",es:"Toda la isla · chofer privado"},
      fleet:[{en:"Business Sedan · 1–3 pax",es:"Sedán Business · 1–3 pax"},{en:"Premium SUV · 1–5 pax",es:"SUV Premium · 1–5 pax"},{en:"Luxury Van · 1–7 pax",es:"Van de Lujo · 1–7 pax"}],
      routes:[{from:"Punta Cana Airport (PUJ)",to:"Casa de Campo",price:"90",min:"60"},{from:"Santo Domingo (SDQ)",to:"Santo Domingo hotels",price:"35",min:"25"},{from:"Full-day",to:"Private driver (8 h)",price:"280",min:"—"}]}
  ],
  co:[
    { id:"cartagena-transfers", name:"Cartagena Transfers", flag:"🇨🇴", currency:"US$",
      tagline:{en:"Walled-city and beach transfers with English-speaking drivers.",es:"Traslados a la ciudad amurallada y playas con choferes que hablan inglés."},
      rating:"4.8", trips:"6,900+", serves:{en:"Cartagena · Barranquilla",es:"Cartagena · Barranquilla"},
      fleet:[{en:"Sedan · 1–3 pax",es:"Sedán · 1–3 pax"},{en:"SUV · 1–5 pax",es:"SUV · 1–5 pax"},{en:"Van · 1–12 pax",es:"Van · 1–12 pax"}],
      routes:[{from:"Cartagena Airport (CTG)",to:"Old City",price:"25",min:"20"},{from:"Cartagena Airport (CTG)",to:"Bocagrande",price:"22",min:"15"},{from:"Cartagena Airport (CTG)",to:"Barú",price:"60",min:"75"}]},
    { id:"andes-shuttle", name:"Andes Shuttle", flag:"🇨🇴", currency:"US$",
      tagline:{en:"City transfers in Bogotá and Medellín, plus day trips to the mountains.",es:"Traslados urbanos en Bogotá y Medellín, y excursiones a la montaña."},
      rating:"4.7", trips:"5,200+", serves:{en:"Bogotá · Medellín",es:"Bogotá · Medellín"},
      fleet:[{en:"Sedan · 1–3 pax",es:"Sedán · 1–3 pax"},{en:"SUV · 1–5 pax",es:"SUV · 1–5 pax"},{en:"Minibus · 1–15 pax",es:"Minibús · 1–15 pax"}],
      routes:[{from:"Bogotá Airport (BOG)",to:"Bogotá hotels",price:"28",min:"40"},{from:"Medellín (MDE)",to:"El Poblado",price:"35",min:"45"},{from:"Medellín (MDE)",to:"Guatapé",price:"120",min:"120"}]},
    { id:"co-premium", name:"Colombia Premium Rides", flag:"🇨🇴", currency:"US$",
      tagline:{en:"Nationwide private chauffeur service with bilingual drivers.",es:"Servicio privado con chofer a nivel nacional y choferes bilingües."},
      rating:"5.0", trips:"2,100+", serves:{en:"Nationwide · private chauffeur",es:"Nacional · chofer privado"},
      fleet:[{en:"Business Sedan · 1–3 pax",es:"Sedán Business · 1–3 pax"},{en:"Premium SUV · 1–5 pax",es:"SUV Premium · 1–5 pax"},{en:"Luxury Van · 1–7 pax",es:"Van de Lujo · 1–7 pax"}],
      routes:[{from:"Any airport",to:"City hotel (private)",price:"60",min:"—"},{from:"Hotel",to:"Airport (private)",price:"60",min:"—"},{from:"Full-day",to:"Private driver (8 h)",price:"300",min:"—"}]}
  ],
  mx:[
    { id:"riviera-transfers", name:"Riviera Maya Transfers", flag:"🇲🇽", currency:"US$",
      tagline:{en:"Reliable Cancún airport rides to the Riviera Maya, with flight tracking.",es:"Traslados confiables del aeropuerto de Cancún a la Riviera Maya, con seguimiento de vuelos."},
      rating:"4.8", trips:"9,800+", serves:{en:"Cancún · Playa del Carmen · Tulum",es:"Cancún · Playa del Carmen · Tulum"},
      fleet:[{en:"Sedan · 1–3 pax",es:"Sedán · 1–3 pax"},{en:"SUV · 1–6 pax",es:"SUV · 1–6 pax"},{en:"Sprinter · 1–14 pax",es:"Sprinter · 1–14 pax"}],
      routes:[{from:"Cancún Airport (CUN)",to:"Playa del Carmen",price:"55",min:"55"},{from:"Cancún Airport (CUN)",to:"Tulum",price:"85",min:"90"},{from:"Cancún Airport (CUN)",to:"Cancún Hotel Zone",price:"30",min:"25"}]},
    { id:"cancun-shuttle", name:"Cancún Shuttle", flag:"🇲🇽", currency:"US$",
      tagline:{en:"Shared and private airport shuttles for Cancún and Puerto Morelos.",es:"Shuttles compartidos y privados de aeropuerto para Cancún y Puerto Morelos."},
      rating:"4.6", trips:"7,400+", serves:{en:"Cancún · Puerto Morelos",es:"Cancún · Puerto Morelos"},
      fleet:[{en:"Shared shuttle",es:"Shuttle compartido"},{en:"Private SUV · 1–6 pax",es:"SUV privado · 1–6 pax"},{en:"Van · 1–14 pax",es:"Van · 1–14 pax"}],
      routes:[{from:"Cancún Airport (CUN)",to:"Puerto Morelos",price:"45",min:"35"},{from:"Cancún Airport (CUN)",to:"Downtown Cancún",price:"28",min:"20"},{from:"Cancún Airport (CUN)",to:"Akumal",price:"70",min:"70"}]},
    { id:"mx-premium", name:"Mexico Premium Rides", flag:"🇲🇽", currency:"US$",
      tagline:{en:"Premium chauffeur service with meet & greet across Mexico.",es:"Servicio premium con chofer y recepción en todo México."},
      rating:"5.0", trips:"2,800+", serves:{en:"Nationwide · private chauffeur",es:"Nacional · chofer privado"},
      fleet:[{en:"Business Sedan · 1–3 pax",es:"Sedán Business · 1–3 pax"},{en:"Premium SUV · 1–5 pax",es:"SUV Premium · 1–5 pax"},{en:"Luxury Van · 1–7 pax",es:"Van de Lujo · 1–7 pax"}],
      routes:[{from:"Cancún Airport (CUN)",to:"Mayakoba",price:"75",min:"45"},{from:"Mexico City (MEX)",to:"City hotels",price:"40",min:"40"},{from:"Full-day",to:"Private driver (8 h)",price:"320",min:"—"}]}
  ],
  pr:[
    { id:"borinquen-shuttle", name:"Borinquen Shuttle", flag:"🇵🇷", currency:"US$",
      tagline:{en:"San Juan airport transfers to Old San Juan, Condado and the east.",es:"Traslados del aeropuerto de San Juan al Viejo San Juan, Condado y el este."},
      rating:"4.8", trips:"4,300+", serves:{en:"San Juan · Fajardo",es:"San Juan · Fajardo"},
      fleet:[{en:"Sedan · 1–3 pax",es:"Sedán · 1–3 pax"},{en:"SUV · 1–5 pax",es:"SUV · 1–5 pax"},{en:"Van · 1–12 pax",es:"Van · 1–12 pax"}],
      routes:[{from:"San Juan Airport (SJU)",to:"Old San Juan",price:"25",min:"20"},{from:"San Juan Airport (SJU)",to:"Condado",price:"22",min:"15"},{from:"San Juan Airport (SJU)",to:"Fajardo",price:"75",min:"60"}]},
    { id:"encanto-transfers", name:"Isla del Encanto Transfers", flag:"🇵🇷", currency:"US$",
      tagline:{en:"Island-wide rides to Dorado, Río Grande and the west coast.",es:"Traslados por toda la isla a Dorado, Río Grande y la costa oeste."},
      rating:"4.7", trips:"3,100+", serves:{en:"San Juan · Rincón",es:"San Juan · Rincón"},
      fleet:[{en:"Sedan · 1–3 pax",es:"Sedán · 1–3 pax"},{en:"SUV · 1–5 pax",es:"SUV · 1–5 pax"},{en:"Minibus · 1–14 pax",es:"Minibús · 1–14 pax"}],
      routes:[{from:"San Juan Airport (SJU)",to:"Dorado",price:"55",min:"40"},{from:"San Juan Airport (SJU)",to:"Rincón",price:"130",min:"150"},{from:"San Juan Airport (SJU)",to:"Río Grande",price:"45",min:"35"}]},
    { id:"pr-premium", name:"Island Premium Rides", flag:"🇵🇷", currency:"US$",
      tagline:{en:"Private chauffeur service with meet & greet across Puerto Rico.",es:"Servicio privado con chofer y recepción en todo Puerto Rico."},
      rating:"5.0", trips:"1,600+", serves:{en:"Island-wide · private chauffeur",es:"Toda la isla · chofer privado"},
      fleet:[{en:"Business Sedan · 1–3 pax",es:"Sedán Business · 1–3 pax"},{en:"Premium SUV · 1–5 pax",es:"SUV Premium · 1–5 pax"},{en:"Luxury Van · 1–7 pax",es:"Van de Lujo · 1–7 pax"}],
      routes:[{from:"Any airport",to:"Hotel (private)",price:"60",min:"—"},{from:"Hotel",to:"Airport (private)",price:"60",min:"—"},{from:"Full-day",to:"Private driver (8 h)",price:"290",min:"—"}]}
  ],
  us:[
    { id:"ny-shuttle", name:"NY Airport Shuttle", flag:"🇺🇸", currency:"US$",
      tagline:{en:"JFK, LaGuardia and Newark transfers into Manhattan and beyond.",es:"Traslados desde JFK, LaGuardia y Newark a Manhattan y alrededores."},
      rating:"4.6", trips:"11,200+", serves:{en:"JFK · LGA · EWR · Manhattan",es:"JFK · LGA · EWR · Manhattan"},
      fleet:[{en:"Sedan · 1–3 pax",es:"Sedán · 1–3 pax"},{en:"SUV · 1–5 pax",es:"SUV · 1–5 pax"},{en:"Van · 1–10 pax",es:"Van · 1–10 pax"}],
      routes:[{from:"JFK Airport",to:"Manhattan",price:"65",min:"60"},{from:"Newark (EWR)",to:"Manhattan",price:"70",min:"55"},{from:"LaGuardia (LGA)",to:"Manhattan",price:"55",min:"40"}]},
    { id:"coast-transfers", name:"USA Coast Transfers", flag:"🇺🇸", currency:"US$",
      tagline:{en:"Theme-park and resort transfers in Orlando, Miami and Las Vegas.",es:"Traslados a parques y resorts en Orlando, Miami y Las Vegas."},
      rating:"4.7", trips:"8,900+", serves:{en:"Orlando · Miami · Las Vegas",es:"Orlando · Miami · Las Vegas"},
      fleet:[{en:"Sedan · 1–3 pax",es:"Sedán · 1–3 pax"},{en:"SUV · 1–6 pax",es:"SUV · 1–6 pax"},{en:"Van · 1–12 pax",es:"Van · 1–12 pax"}],
      routes:[{from:"Orlando (MCO)",to:"Disney area",price:"45",min:"35"},{from:"Miami (MIA)",to:"South Beach",price:"40",min:"30"},{from:"Las Vegas (LAS)",to:"Strip hotels",price:"35",min:"20"}]},
    { id:"us-premium", name:"Premium USA Rides", flag:"🇺🇸", currency:"US$",
      tagline:{en:"Nationwide black-car service with professional chauffeurs.",es:"Servicio de auto ejecutivo a nivel nacional con choferes profesionales."},
      rating:"5.0", trips:"4,200+", serves:{en:"Nationwide · black car service",es:"Nacional · servicio ejecutivo"},
      fleet:[{en:"Business Sedan · 1–3 pax",es:"Sedán Business · 1–3 pax"},{en:"Premium SUV · 1–5 pax",es:"SUV Premium · 1–5 pax"},{en:"Luxury Van · 1–7 pax",es:"Van de Lujo · 1–7 pax"}],
      routes:[{from:"Los Angeles (LAX)",to:"Beverly Hills",price:"90",min:"45"},{from:"Any airport",to:"City hotel (private)",price:"80",min:"—"},{from:"Full-day",to:"Private driver (8 h)",price:"420",min:"—"}]}
  ],
  es:[
    { id:"bcn-transfers", name:"Barcelona Transfers", flag:"🇪🇸", currency:"€",
      tagline:{en:"Airport transfers in Barcelona plus day trips along the Costa Brava.",es:"Traslados de aeropuerto en Barcelona y excursiones por la Costa Brava."},
      rating:"4.8", trips:"7,700+", serves:{en:"Barcelona · Costa Brava",es:"Barcelona · Costa Brava"},
      fleet:[{en:"Sedan · 1–3 pax",es:"Sedán · 1–3 pax"},{en:"SUV · 1–5 pax",es:"SUV · 1–5 pax"},{en:"Van · 1–8 pax",es:"Van · 1–8 pax"}],
      routes:[{from:"Barcelona Airport (BCN)",to:"City center",price:"38",min:"30"},{from:"Barcelona Airport (BCN)",to:"Sitges",price:"70",min:"45"},{from:"Barcelona Airport (BCN)",to:"Costa Brava",price:"160",min:"90"}]},
    { id:"madrid-shuttle", name:"Madrid Shuttle", flag:"🇪🇸", currency:"€",
      tagline:{en:"Madrid airport transfers and trips to Toledo and Segovia.",es:"Traslados del aeropuerto de Madrid y viajes a Toledo y Segovia."},
      rating:"4.7", trips:"6,300+", serves:{en:"Madrid · Toledo",es:"Madrid · Toledo"},
      fleet:[{en:"Sedan · 1–3 pax",es:"Sedán · 1–3 pax"},{en:"SUV · 1–5 pax",es:"SUV · 1–5 pax"},{en:"Minibus · 1–14 pax",es:"Minibús · 1–14 pax"}],
      routes:[{from:"Madrid Airport (MAD)",to:"Madrid hotels",price:"35",min:"30"},{from:"Madrid Airport (MAD)",to:"Toledo",price:"120",min:"60"},{from:"Madrid Airport (MAD)",to:"Segovia",price:"140",min:"75"}]},
    { id:"es-premium", name:"Iberia Premium Rides", flag:"🇪🇸", currency:"€",
      tagline:{en:"Private chauffeur service across Spain, from the Costa del Sol to the islands.",es:"Servicio privado con chofer por toda España, de la Costa del Sol a las islas."},
      rating:"5.0", trips:"2,400+", serves:{en:"Nationwide · private chauffeur",es:"Nacional · chofer privado"},
      fleet:[{en:"Business Sedan · 1–3 pax",es:"Sedán Business · 1–3 pax"},{en:"Premium SUV · 1–5 pax",es:"SUV Premium · 1–5 pax"},{en:"Luxury Van · 1–7 pax",es:"Van de Lujo · 1–7 pax"}],
      routes:[{from:"Málaga (AGP)",to:"Marbella",price:"90",min:"45"},{from:"Palma (PMI)",to:"Palma hotels",price:"45",min:"25"},{from:"Full-day",to:"Private driver (8 h)",price:"340",min:"—"}]}
  ]
};
